import { router } from 'expo-router';
import { StyleSheet, Text, View, useWindowDimensions } from 'react-native';

import { AppIcon, APP_ICONS } from './AppIcon';
import Button from './Button';
import SectionHeading from './SectionHeading';
import StatCard from './StatCard';
import { Colors, Spacing } from '../constants/theme';
import { useAnalyticsSummary } from '../hooks/useAnalyticsSummary';
import { useI18n } from '../i18n';
import { path } from '../navigation';
import { useStore } from '../store/AppStore';

export default function HomepageSections() {
  const { t, fs } = useI18n();
  const { width } = useWindowDimensions();
  const wide = width >= 768;
  const desktop = width >= 1024;
  const { auth, farmer, activeBookingFor, centres } = useStore();
  const analytics = useAnalyticsSummary();
  const isGuest = auth.role !== 'farmer' || !farmer;
  const activeBooking = farmer ? activeBookingFor(farmer.id) : undefined;
  const process = [
    { n: '01', title: t('home.processRegister'), body: t('home.processRegisterBody'), icon: APP_ICONS.personAdd },
    { n: '02', title: t('home.processSubmit'), body: t('home.processSubmitBody'), icon: APP_ICONS.documentText },
    { n: '03', title: t('home.processVerify'), body: t('home.processVerifyBody'), icon: APP_ICONS.shieldCheckmark },
    { n: '04', title: t('home.processPayment'), body: t('home.processPaymentBody'), icon: APP_ICONS.receipt },
  ];
  const values = [
    { title: t('home.valueAccess'), body: t('home.valueAccessBody'), icon: APP_ICONS.location },
    { title: t('home.valuePricing'), body: t('home.valuePricingBody'), icon: APP_ICONS.currency },
    { title: t('home.valueTracking'), body: t('home.valueTrackingBody'), icon: APP_ICONS.pulse },
    { title: t('home.valuePayments'), body: t('home.valuePaymentsBody'), icon: APP_ICONS.wallet },
  ];
  const valueList = values;
  return (
    <>
      <View style={styles.noticeStrip}><View style={styles.noticeLabel}><AppIcon name={APP_ICONS.megaphone} size={13} color={Colors.white} /><Text style={styles.noticeLabelText}>{t('landing.newTag').toUpperCase()}</Text></View><Text style={[styles.noticeText, { fontSize: fs(13) }]}>{t('landing.noticeStrip')}</Text></View>
      <View style={[styles.hero, wide && styles.heroRow]}><View style={styles.heroCopy}><Text style={styles.eyebrow}>{t('home.eyebrow')}</Text><Text style={[styles.heroTitle, { fontSize: fs(desktop ? 42 : 34) }]}>{t('home.heroTitle')}</Text><Text style={styles.heroLead}>{t('home.heroLead')}</Text><View style={styles.heroActions}><Button label={isGuest ? t('home.startSelling') : t('landing.ctaBook')} onPress={() => router.push(isGuest ? path.register : path.booking)} /><Button label={t('home.explore')} variant="outline-primary" onPress={() => router.push(path.centres)} /></View><View style={styles.trustLine}><AppIcon name={APP_ICONS.shieldCheckmark} size={15} color={Colors.green} /><Text style={styles.trustText}>{t('home.trustLine')}</Text></View></View><View style={styles.heroVisual}><Text style={styles.visualKicker}>{t('home.visualKicker')}</Text><Text style={styles.visualTitle}>{t('home.visualTitle')}</Text><View style={styles.routeLine}><View style={styles.routeDot} /><View style={styles.routePath} /><View style={styles.routeDot} /><View style={styles.routePath} /><View style={[styles.routeDot, { backgroundColor: Colors.saffron }]} /></View><View style={styles.visualStats}><Text style={styles.visualNumber}>{centres.length}</Text><Text style={styles.visualLabel}>{t('home.centresConnected')}</Text><Text style={styles.visualNumber}>{analytics.capacityUsedPercent}%</Text><Text style={styles.visualLabel}>{t('home.capacityInUse')}</Text><Text style={styles.visualNumber}>{activeBooking?.token ?? '—'}</Text><Text style={styles.visualLabel}>{activeBooking ? t('home.yourToken') : t('home.noToken')}</Text></View></View></View>
      <View style={styles.metrics}><StatCard label={t('home.farmersConnected')} value={analytics.farmersProcessed} tone="navy" /><StatCard label={t('home.centresConnected')} value={centres.length} tone="grey" /><StatCard label={t('home.capacityInUse')} value={`${analytics.capacityUsedPercent}%`} tone="green" /><StatCard label={t('home.liveUpdates')} value={analytics.live ? t('common.yes') : t('common.mockData')} tone="saffron" /></View>
      <View style={[styles.section, styles.farmerBand, wide && styles.farmerBandRow]}><View style={styles.farmerIntro}><Text style={styles.sectionKicker}>{t('home.farmerKicker')}</Text><Text style={styles.sectionTitle}>{t('home.farmerTitle')}</Text><Text style={styles.sectionLead}>{t('home.farmerLead')}</Text><Button label={t('home.openPortal')} onPress={() => router.push(isGuest ? path.register : path.dashboard)} variant="outline-primary" /></View><View style={styles.values}>{valueList.map((item) => <View key={item.title} style={styles.valueRow}><AppIcon name={item.icon} size={20} color={Colors.primary} /><View style={styles.valueCopy}><Text style={styles.valueTitle}>{item.title}</Text><Text style={styles.valueBody}>{item.body}</Text></View></View>)}</View></View>
      <View style={styles.section}><SectionHeading title={t('home.howTitle')} subtitle={t('home.howSub')} /><View style={styles.processGrid}>{process.map((item) => <View key={item.n} style={styles.processItem}><Text style={styles.processNumber}>{item.n}</Text><AppIcon name={item.icon} size={20} color={Colors.primary} /><Text style={styles.processTitle}>{item.title}</Text><Text style={styles.processBody}>{item.body}</Text></View>)}</View></View>
      <View style={styles.section}><SectionHeading title={t('home.workflowTitle')} subtitle={t('home.workflowSub')} /><View style={styles.workflow}><View style={styles.workflowNode}><Text style={styles.workflowLabel}>{t('home.workflowFarmer')}</Text><Text style={styles.workflowBody}>{t('home.workflowFarmerBody')}</Text></View><Text style={styles.workflowArrow}>→</Text><View style={styles.workflowNode}><Text style={styles.workflowLabel}>{t('home.workflowCentre')}</Text><Text style={styles.workflowBody}>{t('home.workflowCentreBody')}</Text></View><Text style={styles.workflowArrow}>→</Text><View style={styles.workflowNode}><Text style={styles.workflowLabel}>{t('home.workflowMarket')}</Text><Text style={styles.workflowBody}>{t('home.workflowMarketBody')}</Text></View></View></View>
      <View style={[styles.section, styles.transparency, wide && styles.transparencyRow]}><View style={styles.transparencyCopy}><Text style={styles.sectionKicker}>{t('home.transparencyKicker')}</Text><Text style={styles.sectionTitle}>{t('home.transparencyTitle')}</Text><Text style={styles.sectionLead}>{t('home.transparencyLead')}</Text><Button label={t('home.viewToken')} onPress={() => router.push(path.queue)} variant="outline-primary" /></View><View style={styles.record}><View style={styles.recordHeader}><Text style={styles.recordTitle}>{t('home.recordTitle')}</Text><Text style={styles.recordStatus}>{activeBooking ? t('home.recordActive') : t('home.recordDemo')}</Text></View>{['home.recordOne' as const, 'home.recordTwo' as const, 'home.recordThree' as const].map((key, index) => <View key={key} style={styles.recordRow}><Text style={styles.recordMark}>{index + 1}</Text><Text style={styles.recordText}>{t(key)}</Text><AppIcon name={APP_ICONS.checkmarkCircle} size={16} color={Colors.green} /></View>)}</View></View>
      <View style={styles.finalCta}><Text style={[styles.finalTitle, { fontSize: fs(desktop ? 28 : 24) }]}>{t('home.finalTitle')}</Text><Text style={styles.finalLead}>{t('home.finalLead')}</Text><Button label={t('home.enterPortal')} onPress={() => router.push(isGuest ? path.login : path.dashboard)} /></View>
    </>
  );
}

const styles = StyleSheet.create({
  noticeStrip: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.saffronLight, borderWidth: 1, borderColor: Colors.saffron, padding: Spacing.sm, marginBottom: Spacing.xl },
  noticeLabel: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: Colors.saffronDark, paddingHorizontal: 6, paddingVertical: 3, marginRight: Spacing.sm }, noticeLabelText: { color: Colors.white, fontWeight: '800', fontSize: 10 }, noticeText: { color: Colors.saffronDark, fontWeight: '700', flex: 1 },
  hero: { backgroundColor: Colors.white, borderWidth: 1, borderColor: Colors.border, padding: Spacing.xl, marginBottom: Spacing.xl }, heroRow: { flexDirection: 'row', gap: Spacing.xl }, heroCopy: { flex: 1.1, justifyContent: 'center' }, heroVisual: { flex: 0.9, minHeight: 250, backgroundColor: Colors.primaryLight, borderLeftWidth: 4, borderLeftColor: Colors.primary, padding: Spacing.lg, justifyContent: 'space-between' }, eyebrow: { color: Colors.primary, fontWeight: '800', letterSpacing: 1, textTransform: 'uppercase', marginBottom: Spacing.md, fontSize: 12 }, heroTitle: { color: Colors.primaryDark, fontWeight: '800', lineHeight: 1.08, marginBottom: Spacing.md }, heroLead: { color: Colors.textSecondary, fontSize: 15, lineHeight: 23, maxWidth: 560, marginBottom: Spacing.xl }, heroActions: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md }, trustLine: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: Spacing.lg }, trustText: { color: Colors.textSecondary, fontSize: 12, fontWeight: '600' }, visualKicker: { color: Colors.primary, fontSize: 11, fontWeight: '800', textTransform: 'uppercase' }, visualTitle: { color: Colors.primaryDark, fontSize: 22, fontWeight: '800', marginTop: 6 }, routeLine: { flexDirection: 'row', alignItems: 'center', marginVertical: Spacing.xl }, routeDot: { width: 14, height: 14, borderRadius: 7, backgroundColor: Colors.primary }, routePath: { flex: 1, height: 2, backgroundColor: Colors.primary }, visualStats: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: Colors.primary, paddingTop: Spacing.md }, visualNumber: { color: Colors.primaryDark, fontSize: 20, fontWeight: '800' }, visualLabel: { color: Colors.textSecondary, fontSize: 10, marginBottom: Spacing.sm },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md, marginBottom: Spacing.xl }, section: { marginBottom: Spacing.xl }, processGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md }, processItem: { flex: 1, minWidth: 160, borderTopWidth: 2, borderTopColor: Colors.primary, paddingTop: Spacing.md }, processNumber: { color: Colors.saffron, fontWeight: '800', fontSize: 18, marginBottom: Spacing.md }, processTitle: { color: Colors.primaryDark, fontWeight: '800', marginTop: Spacing.sm, marginBottom: 4 }, processBody: { color: Colors.textSecondary, lineHeight: 19 }, farmerBand: { backgroundColor: Colors.surfaceAlt, borderTopWidth: 4, borderTopColor: Colors.saffron, padding: Spacing.xl }, farmerBandRow: { flexDirection: 'row', gap: Spacing.xl }, farmerIntro: { flex: 1 }, values: { flex: 1, gap: Spacing.md }, sectionKicker: { color: Colors.primary, fontWeight: '800', fontSize: 11, textTransform: 'uppercase', marginBottom: Spacing.sm }, sectionTitle: { color: Colors.primaryDark, fontWeight: '800', fontSize: 26, marginBottom: Spacing.sm }, sectionLead: { color: Colors.textSecondary, lineHeight: 22, marginBottom: Spacing.lg }, valueRow: { flexDirection: 'row', gap: Spacing.md, borderBottomWidth: 1, borderBottomColor: Colors.border, paddingVertical: Spacing.sm }, valueCopy: { flex: 1 }, valueTitle: { color: Colors.text, fontWeight: '800', marginBottom: 2 }, valueBody: { color: Colors.textSecondary, lineHeight: 18 },
  workflow: { flexDirection: 'row', gap: Spacing.md, backgroundColor: Colors.white, borderWidth: 1, borderColor: Colors.border, padding: Spacing.lg }, workflowNode: { flex: 1, backgroundColor: Colors.surfaceAlt, padding: Spacing.md, borderLeftWidth: 3, borderLeftColor: Colors.primary }, workflowLabel: { color: Colors.primaryDark, fontWeight: '800', marginBottom: 5 }, workflowBody: { color: Colors.textSecondary, lineHeight: 18 }, workflowArrow: { color: Colors.primary, fontSize: 22, alignSelf: 'center' },
  transparency: { flexDirection: 'column', backgroundColor: Colors.primaryLight, borderLeftWidth: 4, borderLeftColor: Colors.primary, padding: Spacing.xl }, transparencyRow: { flexDirection: 'row', gap: Spacing.xl }, transparencyCopy: { flex: 1 }, record: { flex: 1, backgroundColor: Colors.white, borderWidth: 1, borderColor: Colors.border, padding: Spacing.lg, marginTop: Spacing.lg }, recordHeader: { flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: Colors.border, paddingBottom: Spacing.md, marginBottom: Spacing.sm }, recordTitle: { color: Colors.primaryDark, fontWeight: '800' }, recordStatus: { color: Colors.green, fontWeight: '800', fontSize: 12 }, recordRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, paddingVertical: Spacing.sm }, recordMark: { width: 24, height: 24, borderRadius: 12, backgroundColor: Colors.primaryLight, color: Colors.primary, textAlign: 'center', lineHeight: 24, fontWeight: '800', fontSize: 12 }, recordText: { flex: 1, color: Colors.text, fontSize: 13 }, finalCta: { alignItems: 'center', paddingVertical: Spacing.xxl, paddingHorizontal: Spacing.lg, borderTopWidth: 1, borderTopColor: Colors.border, marginBottom: Spacing.lg }, finalTitle: { color: Colors.primaryDark, fontWeight: '800', textAlign: 'center', marginBottom: Spacing.sm }, finalLead: { color: Colors.textSecondary, textAlign: 'center', marginBottom: Spacing.lg, lineHeight: 22 },
});
